openapi: 3.0.3
info:
  title: Workflow Coordinator API
  description: API for managing multi-agent workflow orchestration
  version: 1.0.0

servers:
  - url: /api/workflow
    description: Workflow coordinator endpoints

paths:
  /workflows:
    post:
      summary: Create a new workflow
      description: Initialize a multi-agent workflow with task description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - description
              properties:
                description:
                  type: string
                  description: Human-readable task description
                  example: "Build a login form with validation"
                requirements:
                  type: array
                  items:
                    type: string
                  description: Optional additional requirements
                  example: ["Must support email validation", "Should have password strength indicator"]
      responses:
        '201':
          description: Workflow created successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - workflowId
                  - status
                properties:
                  workflowId:
                    type: string
                    format: uuid
                    description: Unique workflow identifier
                  status:
                    type: string
                    enum: [idle, in_progress, paused, completed, failed]
                    description: Initial workflow status
                  estimatedDuration:
                    type: integer
                    description: Estimated completion time in seconds
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error

  /workflows/{workflowId}:
    get:
      summary: Get workflow status
      description: Retrieve current state of a workflow
      parameters:
        - name: workflowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Workflow identifier
      responses:
        '200':
          description: Workflow status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStatus'
        '404':
          description: Workflow not found
        '500':
          description: Internal server error

    put:
      summary: Update workflow state
      description: Pause, resume, or cancel a workflow
      parameters:
        - name: workflowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Workflow identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - action
              properties:
                action:
                  type: string
                  enum: [pause, resume, cancel]
                  description: Action to perform on workflow
      responses:
        '200':
          description: Workflow updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStatus'
        '400':
          description: Invalid action or workflow state
        '404':
          description: Workflow not found
        '500':
          description: Internal server error

  /workflows/{workflowId}/artifacts:
    get:
      summary: Get workflow artifacts
      description: Retrieve all artifacts generated by the workflow
      parameters:
        - name: workflowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Workflow identifier
      responses:
        '200':
          description: Artifacts retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artifact'
        '404':
          description: Workflow not found
        '500':
          description: Internal server error

  /workflows/{workflowId}/events:
    get:
      summary: Subscribe to workflow events
      description: Get real-time updates about workflow state changes
      parameters:
        - name: workflowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Workflow identifier
        - name: since
          in: query
          schema:
            type: integer
            format: int64
          description: Timestamp to get events since (Unix timestamp)
      responses:
        '200':
          description: Event stream established
          content:
            text/event-stream:
              schema:
                type: object
                properties:
                  event:
                    type: string
                    enum: [started, agent_changed, task_completed, completed, failed, paused]
                  data:
                    type: object
                    description: Event-specific data
                  timestamp:
                    type: integer
                    format: int64
        '404':
          description: Workflow not found

components:
  schemas:
    WorkflowStatus:
      type: object
      required:
        - id
        - status
        - currentAgent
        - progress
        - tasks
      properties:
        id:
          type: string
          format: uuid
          description: Workflow identifier
        status:
          type: string
          enum: [idle, in_progress, paused, completed, failed]
          description: Current workflow status
        currentAgent:
          type: string
          enum: [ProjectManager, Designer, Frontend, Backend, Tester]
          nullable: true
          description: Currently active agent
        progress:
          type: number
          minimum: 0
          maximum: 100
          description: Completion percentage
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
          description: All tasks in the workflow
        createdAt:
          type: string
          format: date-time
          description: Workflow creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    Task:
      type: object
      required:
        - id
        - description
        - assignedAgent
        - status
      properties:
        id:
          type: string
          format: uuid
          description: Task identifier
        description:
          type: string
          description: Task description
        assignedAgent:
          type: string
          enum: [ProjectManager, Designer, Frontend, Backend, Tester]
          description: Agent assigned to task
        status:
          type: string
          enum: [pending, active, completed, failed]
          description: Task execution status
        dependencies:
          type: array
          items:
            type: string
            format: uuid
          description: Task IDs that must complete first
        progress:
          type: number
          minimum: 0
          maximum: 100
          description: Task completion percentage
        startedAt:
          type: string
          format: date-time
          nullable: true
          description: Task start timestamp
        completedAt:
          type: string
          format: date-time
          nullable: true
          description: Task completion timestamp

    Artifact:
      type: object
      required:
        - id
        - type
        - name
        - content
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          description: Artifact identifier
        type:
          type: string
          enum: [requirement, design_spec, component_code, api_spec, test_plan]
          description: Type of artifact
        name:
          type: string
          description: Human-readable artifact name
        content:
          type: string
          description: Artifact content (markdown, code, etc.)
        createdBy:
          type: string
          enum: [ProjectManager, Designer, Frontend, Backend, Tester]
          description: Agent that created the artifact
        createdAt:
          type: string
          format: date-time
          description: Artifact creation timestamp
